version: 0.0
os: linux

files:
  - source: /
    destination: /home/root/calculator

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      runas: ec2-user
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: ec2-user
